# Generated by Django 2.2 on 2019-07-16 10:48

import IDN_APP.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permintaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_permintaan', models.CharField(default=IDN_APP.models.Permintaan.number, max_length=20)),
                ('nama_client', models.CharField(max_length=50)),
                ('alamat', models.CharField(default='', max_length=80)),
                ('perusahaan', models.CharField(max_length=25)),
                ('no_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('jumlah_permintaan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=30)),
                ('nomor_PO', models.CharField(default=IDN_APP.models.PurchaseOrder.number, max_length=20)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('Perusahaan', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(default=IDN_APP.models.Training.number, max_length=20)),
                ('nama_training', models.CharField(blank=True, default='', max_length=25)),
                ('harga', models.IntegerField()),
                ('lokasi', models.CharField(max_length=20)),
                ('keterangan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Penawaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pnw', models.CharField(default=IDN_APP.models.Penawaran.number, max_length=20)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('Lokasi', models.CharField(choices=[('JAKARTA', 'Jakarta'), ('BODETABEK', 'Bodetabek'), ('LUAR BODETABEK', 'Luar Bodetabek')], max_length=20)),
                ('nama_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IDN_APP.Permintaan')),
                ('training', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='IDN_APP.Training')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_inv', models.CharField(default=IDN_APP.models.Invoice.number, max_length=20)),
                ('tgl_inv', models.DateField(auto_now_add=True)),
                ('Jumlah', models.PositiveIntegerField(default='')),
                ('Nama_Client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IDN_APP.PurchaseOrder')),
                ('Training', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='IDN_APP.Training')),
            ],
        ),
    ]
