# Generated by Django 2.1.2 on 2019-10-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDN_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='nama_training',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
